
'use client';

import { useState, useEffect } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { PlusCircle, Trash2, Loader2, Save, Sparkles } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Separator } from '../ui/separator';
import { createProfileSummaryAction } from '@/lib/actions';
import { Skeleton } from '../ui/skeleton';

const profileFormSchema = z.object({
  subjects: z
    .array(
      z.object({
        name: z.string().min(1, { message: 'Subject name cannot be empty.' }),
        mark: z.coerce
          .number()
          .min(0, { message: 'Mark must be at least 0.' })
          .max(100, { message: 'Mark cannot exceed 100.' }),
      })
    )
    .min(1, { message: 'At least one subject is required.' }),
});

type ProfileFormValues = z.infer<typeof profileFormSchema>;

// Mock data, later we'll replace this with a global state
const initialSubjects = [
    { name: 'Math', mark: 85 },
    { name: 'History', mark: 72 },
    { name: 'Science', mark: 91 },
    { name: 'Literature', mark: 65 },
    { name: 'Coding', mark: 78 },
];


export function ProfileClient() {
  const [isLoading, setIsLoading] = useState(false);
  const [isSummaryLoading, setIsSummaryLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const { toast } = useToast();

  const form = useForm<ProfileFormValues>({
    resolver: zodResolver(profileFormSchema),
    defaultValues: {
      subjects: initialSubjects,
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: 'subjects',
  });

  const subjectsValue = form.watch('subjects');

  const generateSummary = async (values: ProfileFormValues) => {
    setIsSummaryLoading(true);
    setSummary(null);
    if (!values.subjects || values.subjects.length === 0 || values.subjects.some(s => !s.name)) {
        setIsSummaryLoading(false);
        return;
    }
    const result = await createProfileSummaryAction(values);
    if (result.success && result.data) {
      setSummary(result.data.summary);
    } else {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Could not generate AI summary.',
      });
    }
    setIsSummaryLoading(false);
  }

  // Generate summary on initial load and when subjects change
  useEffect(() => {
    generateSummary({ subjects: subjectsValue });
  }, [subjectsValue]);

  async function onSubmit(values: ProfileFormValues) {
    setIsLoading(true);
    
    // Here you would typically save the data to a backend or global state
    await new Promise(resolve => setTimeout(resolve, 1000));
    console.log(values);

    toast({
      title: 'Profile Saved',
      description: 'Your subjects and marks have been updated.',
    });
    
    setIsLoading(false);
    // The summary will be regenerated by the useEffect hook
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2">
        <Card>
            <CardHeader>
              <CardTitle>Your Subjects</CardTitle>
              <CardDescription>
                Add your subjects and current marks (out of 100) to see them on your dashboard.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
                  <div className="space-y-4">
                    {fields.map((field, index) => (
                      <div key={field.id} className="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
                        <FormField
                          control={form.control}
                          name={`subjects.${index}.name`}
                          render={({ field }) => (
                            <FormItem className="md:col-span-2">
                              <FormLabel>Subject</FormLabel>
                              <FormControl>
                                <Input placeholder="e.g., Physics" {...field} />
                              </FormControl>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                        <FormField
                          control={form.control}
                          name={`subjects.${index}.mark`}
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel>Mark (%)</FormLabel>
                              <div className="flex items-center gap-2">
                                <FormControl>
                                    <Input type="number" placeholder="e.g., 88" {...field} />
                                </FormControl>
                                <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => remove(index)}
                                    disabled={fields.length <= 1}
                                >
                                    <Trash2 className="h-4 w-4 text-destructive" />
                                </Button>
                              </div>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                      </div>
                    ))}
                  </div>
                  <Separator />
                  <div className="flex justify-between items-center">
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => append({ name: '', mark: 0 })}
                    >
                      <PlusCircle className="mr-2 h-4 w-4" />
                      Add Subject
                    </Button>
                    <Button type="submit" disabled={isLoading}>
                      {isLoading ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : <Save className="mr-2 h-4 w-4" />}
                      Save Changes
                    </Button>
                  </div>
                  <FormMessage>{form.formState.errors.subjects?.message}</FormMessage>
                </form>
              </Form>
            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-1">
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Sparkles className="text-primary h-6 w-6" />
                        AI Summary
                    </CardTitle>
                    <CardDescription>
                        A quick overview of your academic performance based on your marks.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {isSummaryLoading && (
                        <div className="space-y-2">
                            <Skeleton className="h-4 w-full" />
                            <Skeleton className="h-4 w-full" />
                            <Skeleton className="h-4 w-3/4" />
                        </div>
                    )}
                    {summary && !isSummaryLoading && (
                        <p className="text-sm text-muted-foreground">{summary}</p>
                    )}
                    {!summary && !isSummaryLoading && (
                        <p className="text-sm text-center text-muted-foreground py-8">Enter your subjects and marks to generate a summary.</p>
                    )}
                </CardContent>
            </Card>
        </div>
    </div>
  );
}
