// This file is automatically generated by Firebase Studio.
// Do not edit.

/* eslint-disable */

// The following is the configuration for the Firebase project used by this
// application. You can find this information in the Firebase console.
// This configuration is PUBLIC and can be freely shared. It is NOT a secret.

/**
 * The Firebase configuration object.
 */
export const firebaseConfig = {
  "apiKey": "from-firebase-studio",
  "authDomain": "from-firebase-studio",
  "projectId": "from-firebase-studio",
  "storageBucket": "from-firebase-studio",
  "messagingSenderId": "from-firebase-studio",
  "appId": "from-firebase-studio",
  "measurementId": "from-firebase-studio"
};

/**
 * The project ID of the Firebase project used by this application.
 */
export const firebaseProjectId = "from-firebase-studio";
